# courtesy of
# https://github.com/EndlessEscapade/endless-escapade/blob/dev/.github/workflows/lint.yml
name: Linter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore .NET dependencies
      run: dotnet restore

    - name: Lint
      run: dotnet format style UICustomizer.sln --verify-no-changes
